// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'multiplos-c68c4',
    appId: '1:30783296163:web:0797c8523fae8c2f76e516',
    storageBucket: 'multiplos-c68c4.appspot.com',
    apiKey: 'AIzaSyCUXhFYw2_1mTufRSPP2e4meXibU-cWe2s',
    authDomain: 'multiplos-c68c4.firebaseapp.com',
    messagingSenderId: '30783296163',
    measurementId: 'G-L73RCTR2X0',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES'],
};
